-- ============================================================
--  BioMeLab — Script DDL Completo
--  Banco: Oracle SQL
--  Ordem de criação respeitando dependências
-- ============================================================


-- ------------------------------------------------------------
-- 1. T_BIOMELAB_USUARIO
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_USUARIO (
    id_usuario      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_usuario      VARCHAR2(50)    NOT NULL,
    dt_nascimento   DATE            NOT NULL,
    email           VARCHAR2(50)    NOT NULL,
    senha           VARCHAR2(50)    NOT NULL,

    CONSTRAINT uq_usuario_email UNIQUE (email)
);


-- ------------------------------------------------------------
-- 2. T_BIOMELAB_LOCALIDADE
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_LOCALIDADE (
    id_localidade   INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_planeta      VARCHAR2(50)    NOT NULL,
    continente      VARCHAR2(30),
    pais            VARCHAR2(30)
);


-- ------------------------------------------------------------
-- 3. T_BIOMELAB_AMBIENTE
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_AMBIENTE (
    id_ambiente     INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_ambiente     VARCHAR2(100)   NOT NULL,
    st_visibilidade CHAR(1)         NOT NULL,
    st_ativo        VARCHAR2(7),
    fk_usuario      INTEGER,

    CONSTRAINT fk_ambiente_usuario
        FOREIGN KEY (fk_usuario)
        REFERENCES T_BIOMELAB_USUARIO(id_usuario),

    CONSTRAINT ck_ambiente_visibilidade
        CHECK (st_visibilidade IN ('P', 'R')),

    CONSTRAINT ck_ambiente_ativo
        CHECK (st_ativo IS NULL OR st_ativo IN ('ATIVO', 'INATIVO')),

    CONSTRAINT ck_publico_sem_usuario
        CHECK (
            st_visibilidade = 'R'
            OR (st_visibilidade = 'P' AND fk_usuario IS NULL AND st_ativo IS NULL)
        ),

    CONSTRAINT ck_privado_com_usuario
        CHECK (
            st_visibilidade = 'P'
            OR (st_visibilidade = 'R' AND fk_usuario IS NOT NULL AND st_ativo IS NOT NULL)
        )
);


-- ------------------------------------------------------------
-- 4. AMBIENTE_LOCALIDADE
-- ------------------------------------------------------------
CREATE TABLE AMBIENTE_LOCALIDADE (
    fk_localidade   INTEGER NOT NULL,
    fk_ambiente     INTEGER NOT NULL,

    CONSTRAINT pk_ambiente_localidade
        PRIMARY KEY (fk_localidade, fk_ambiente),

    CONSTRAINT fk_ambloc_localidade
        FOREIGN KEY (fk_localidade)
        REFERENCES T_BIOMELAB_LOCALIDADE(id_localidade),

    CONSTRAINT fk_ambloc_ambiente
        FOREIGN KEY (fk_ambiente)
        REFERENCES T_BIOMELAB_AMBIENTE(id_ambiente)
);


-- ------------------------------------------------------------
-- 5. T_BIOMELAB_CONJ_PROPS_ATUAL
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_CONJ_PROPS_ATUAL (
    id_conj_props_atual    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vl_temperatura         NUMERIC(20,5) NOT NULL,
    vl_umidade             NUMERIC(60,2) NOT NULL,
    vl_luminosidade        NUMERIC(17,5) NOT NULL,
    vl_gravidade           NUMERIC(20,5),
    pressao_atmosferica    NUMERIC(15,2),

    fk_ambiente            INTEGER NOT NULL,

    CONSTRAINT fk_props_atual_ambiente
        FOREIGN KEY (fk_ambiente)
        REFERENCES T_BIOMELAB_AMBIENTE(id_ambiente),

    CONSTRAINT uq_props_atual_ambiente
        UNIQUE (fk_ambiente)
);


-- ------------------------------------------------------------
-- 6. T_BIOMELAB_ESTUDO
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_ESTUDO (
    id_estudo       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_estudo       VARCHAR2(50) NOT NULL,
    des_estudo      VARCHAR2(200),
    fk_ambiente     INTEGER NOT NULL,

    CONSTRAINT fk_estudo_ambiente
        FOREIGN KEY (fk_ambiente)
        REFERENCES T_BIOMELAB_AMBIENTE(id_ambiente),

    CONSTRAINT uq_estudo_ambiente
        UNIQUE (fk_ambiente)
);


-- ------------------------------------------------------------
-- 7. T_BIOMELAB_TESTE
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_TESTE (
    id_teste                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_teste                VARCHAR2(100),

    dt_inicio_teste         DATE,
    dt_termino_teste        DATE,

    obs_gerais              VARCHAR2(4000),
    conclusao               VARCHAR2(4000),

    fk_estudo               INTEGER NOT NULL,

    CONSTRAINT fk_teste_estudo
        FOREIGN KEY (fk_estudo)
        REFERENCES T_BIOMELAB_ESTUDO(id_estudo)
);


-- ------------------------------------------------------------
-- 8. T_BIOMELAB_CONJ_PROPS_SNAPSHOT
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_CONJ_PROPS_SNAPSHOT (
    id_conj_props_snapshot    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    vl_temperatura            NUMERIC(20,5) NOT NULL,
    vl_umidade                NUMERIC(60,2) NOT NULL,
    vl_luminosidade           NUMERIC(17,5) NOT NULL,

    vl_gravidade              NUMERIC(20,5),
    pressao_atmosferica       NUMERIC(15,2),

    fk_teste                  INTEGER NOT NULL,

    CONSTRAINT fk_snapshot_teste
        FOREIGN KEY (fk_teste)
        REFERENCES T_BIOMELAB_TESTE(id_teste),

    CONSTRAINT uq_snapshot_teste
        UNIQUE (fk_teste)
);


-- ============================================================
--  FIM DO SCRIPT
-- ============================================================