-- ============================================================
--  BioMeLab — Script DDL Completo
--  Banco: Oracle SQL
--  Ordem de criação respeitando dependências
-- ============================================================


-- ------------------------------------------------------------
-- 1. T_BIOMELAB_USUARIO
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_USUARIO (
    id_usuario      INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_usuario      VARCHAR2(50)    NOT NULL,
    dt_nascimento   DATE            NOT NULL,
    email           VARCHAR2(50)    NOT NULL,
    senha           VARCHAR2(50)    NOT NULL,

    CONSTRAINT uq_usuario_email UNIQUE (email)
);


-- ------------------------------------------------------------
-- 2. T_BIOMELAB_LOCALIDADE
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_LOCALIDADE (
    id_localidade   INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_planeta      VARCHAR2(50)    NOT NULL,
    continente      VARCHAR2(30),
    pais            VARCHAR2(30)
);


-- ------------------------------------------------------------
-- 3. T_BIOMELAB_AMBIENTE
--    - Ambientes públicos:  id_usuario = NULL, st_ativo = NULL
--    - Ambientes privados:  id_usuario NOT NULL, st_ativo IN ('ATIVO','INATIVO')
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_AMBIENTE (
    id_ambiente     INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_ambiente     VARCHAR2(100)   NOT NULL,
    st_visibilidade CHAR(1)         NOT NULL,
    st_ativo        VARCHAR2(7),
    id_usuario      INTEGER,


    -- Visibilidade só aceita 'P' (público) ou 'R' (privado)
    CONSTRAINT ck_ambiente_visibilidade
        CHECK (st_visibilidade IN ('P', 'R')),

    -- st_ativo só aceita NULL, 'ATIVO' ou 'INATIVO'
    CONSTRAINT ck_ambiente_ativo
        CHECK (st_ativo IS NULL OR st_ativo IN ('ATIVO', 'INATIVO')),

    -- Ambiente público: sem usuário e sem st_ativo
    CONSTRAINT ck_publico_sem_usuario
        CHECK (
            st_visibilidade = 'R'
            OR (st_visibilidade = 'P' AND id_usuario IS NULL AND st_ativo IS NULL)
        ),

    -- Ambiente privado: obrigatoriamente tem usuário e st_ativo
    CONSTRAINT ck_privado_com_usuario
        CHECK (
            st_visibilidade = 'P'
            OR (st_visibilidade = 'R' AND id_usuario IS NOT NULL AND st_ativo IS NOT NULL)
        )
);



-- ------------------------------------------------------------
-- 4. AMBIENTE_LOCALIDADE  (N:N entre AMBIENTE e LOCALIDADE)
--    - Um ambiente pode existir sem localidades
--    - Toda localidade deve pertencer a pelo menos um ambiente
--      (regra garantida na aplicação)
-- ------------------------------------------------------------
CREATE TABLE AMBIENTE_LOCALIDADE (
    id_localidade   INTEGER     NOT NULL,
    id_ambiente     INTEGER     NOT NULL,

    CONSTRAINT pk_ambiente_localidade
        PRIMARY KEY (id_localidade, id_ambiente),

    CONSTRAINT fk_ambloc_localidade
        FOREIGN KEY (id_localidade) REFERENCES T_BIOMELAB_LOCALIDADE (id_localidade),

    CONSTRAINT fk_ambloc_ambiente
        FOREIGN KEY (id_ambiente) REFERENCES T_BIOMELAB_AMBIENTE (id_ambiente)
);


-- ------------------------------------------------------------
-- 5. T_BIOMELAB_CONJUNTO_PROPRIEDADES
--    - Representa o ESTADO ATUAL dos sensores (não é histórico)
--    - Relacionamento 1:1 com AMBIENTE (garantido pela UNIQUE na FK)
--    - temperatura, umidade e luminosidade são obrigatórios
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_CONJUNTO_PROPRIEDADES (
    id_conjunto_propriedades    INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vl_temperatura              NUMERIC(20,5)   NOT NULL,
    vl_umidade                  NUMERIC(60,2)   NOT NULL,
    vl_luminosidade             NUMERIC(17,5)   NOT NULL,
    vl_gravidade                NUMERIC(20,5),
    pressao_atmosferica         NUMERIC(15,2),
    id_ambiente                 INTEGER         NOT NULL,

    CONSTRAINT fk_propriedades_ambiente
        FOREIGN KEY (id_ambiente) REFERENCES T_BIOMELAB_AMBIENTE (id_ambiente),

    -- Garante 1:1 com AMBIENTE
    CONSTRAINT uq_propriedades_ambiente
        UNIQUE (id_ambiente)
);



-- ------------------------------------------------------------
-- 6. T_BIOMELAB_ESTUDO
--    - Criado a partir de um ambiente PRIVADO
--    - Relacionamento 1:1 com AMBIENTE (garantido pela UNIQUE na FK)
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_ESTUDO (
    id_estudo       INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_estudo       VARCHAR2(50)    NOT NULL,
    des_estudo      VARCHAR2(200),
    id_ambiente     INTEGER         NOT NULL,

    CONSTRAINT fk_estudo_ambiente
        FOREIGN KEY (id_ambiente) REFERENCES T_BIOMELAB_AMBIENTE (id_ambiente),

    -- Garante 1:1 com AMBIENTE
    CONSTRAINT uq_estudo_ambiente
        UNIQUE (id_ambiente)
);



-- ------------------------------------------------------------
-- 7. T_BIOMELAB_TESTES
--    - Todo teste precisa de um estudo (id_estudo NOT NULL)
--    - Um estudo pode ter vários testes (1:N)
-- ------------------------------------------------------------
CREATE TABLE T_BIOMELAB_TESTES (
    id_teste            INTEGER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_teste            VARCHAR2(100),
    dt_inicio_teste     DATE,
    dt_termino_teste    DATE,
    obs_gerais          VARCHAR2(4000),
    conclusao           VARCHAR2(4000),
    id_estudo           INTEGER         NOT NULL,

    CONSTRAINT fk_testes_estudo
        FOREIGN KEY (id_estudo) REFERENCES T_BIOMELAB_ESTUDO (id_estudo)
);


-- ============================================================
--  FIM DO SCRIPT
-- ============================================================
